### ISSUE TITLE
ValueError: time data '2016' does not match format '%d %B %Y'

### ISSUE THREAD

**Issue by bohdanbobrowski** [bohdanbobrowski/blogspot2epub#3]
``'blog2epub franklinsghost.blogspot.com
1. Russell Potter and John Geiger
...
39. The Muster
40. Essential Franklin Reading
Traceback (most recent call last):
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/bin/blog2epub", line 11, in <module>
    load_entry_point('blog2epub==1.0', 'console_scripts', 'blog2epub')()
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Blog2EpubCli.py", line 71, in run
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Blog2EpubCli.py", line 30, in __init__
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Blog2Epub.py", line 17, in download
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/crawlers/Crawler.py", line 162, in save
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Book.py", line 81, in __init__
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Book.py", line 91, in update_file_name
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2016' does not match format '%d %B %Y'
```

**Comment by bohdanbobrowski** [comment]
Fixed. I'm using now awesome python-dateutil library to parse article creation date.
