### ISSUE TITLE
OSError: cannot identify image file './temp/buildingterror.blogspot.com/originals/88e9e15a4769b5cc89ccb22a58d50d65..htm'

### ISSUE THREAD

**Issue by bohdanbobrowski** [bohdanbobrowski/blogspot2epub#4]
```
blog2epub buildingterror.blogspot.com
1. A MAN-HAULED BOAT SLEDGE FROM HMS TERROR
Traceback (most recent call last):
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/bin/blog2epub", line 11, in <module>
    load_entry_point('blog2epub==1.0', 'console_scripts', 'blog2epub')()
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Blog2EpubCli.py", line 71, in run
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Blog2EpubCli.py", line 30, in __init__
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Blog2Epub.py", line 17, in download
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/crawlers/Crawler.py", line 161, in save
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/crawlers/Crawler.py", line 156, in _crawl
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/crawlers/Crawler.py", line 131, in _articles_loop
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/crawlers/Crawler.py", line 367, in process
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/crawlers/Crawler.py", line 319, in _get_images
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/crawlers/Crawler.py", line 312, in _process_images
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/crawlers/Crawler.py", line 249, in download_image
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/PIL/Image.py", line 2705, in open
    % (filename if filename else fp))
OSError: cannot identify image file './temp/buildingterror.blogspot.com/originals/88e9e15a4769b5cc89ccb22a58d50d65..htm'`
```

**Comment by bohdanbobrowski** [comment]
Better error handling and improved cover generation implemented.
