### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by bohdanbobrowski** [bohdanbobrowski/blogspot2epub#5]
```
blog2epub brucecameronelliott.blogspot.com
Traceback (most recent call last):
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/bin/blog2epub", line 11, in <module>
    load_entry_point('blog2epub==1.0', 'console_scripts', 'blog2epub')()
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Blog2EpubCli.py", line 71, in run
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Blog2EpubCli.py", line 30, in __init__
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Blog2Epub.py", line 17, in download
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/crawlers/Crawler.py", line 163, in save
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Book.py", line 206, in save
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Book.py", line 138, in _add_cover
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/blog2epub-1.0-py3.6.egg/blog2epub/Cover.py", line 88, in generate
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/PIL/ImageDraw.py", line 263, in text
    if self._multiline_check(text):
  File "/home/bohdan/Skrypty/python/blogspot2epub/venv/lib/python3.6/site-packages/PIL/ImageDraw.py", line 254, in _multiline_check
    return split_character in text
TypeError: argument of type 'NoneType' is not iterable```

**Comment by bohdanbobrowski** [comment]
Added support for atom feed - still rather experimental - but exception described above doesn't occur currently.
